services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: video_analyzer_backend
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: video_analyzer_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend